# YourMeet — Multilingual Strings
# Add new languages by adding a new key to each dict

LANGUAGES = {
    "en": "🇬🇧 English",
    "es": "🇪🇸 Español",
    "ru": "🇷🇺 Русский",
    "ko": "🇰🇷 한국어",
    "zh": "🇨🇳 中文",
    "id": "🇮🇩 Indonesia",
    "ar": "🇸🇦 العربية",
    "pt": "🇧🇷 Português",
    "fr": "🇫🇷 Français",
    "de": "🇩🇪 Deutsch",
    "hi": "🇮🇳 हिंदी",
    "tr": "🇹🇷 Türkçe",
    "it": "🇮🇹 Italiano",
    "ja": "🇯🇵 日本語",
}

STRINGS = {
    "en": {
        "language_select": "🌍 Please select your language:",
        "welcome": "Hey {name}! 👋\n\nWelcome to *YourMeet* 💕\n\n🔥 Swipe & discover people\n⭐ Send super likes\n💕 Match & connect\n👑 Go Premium for unlimited access\n\nTap below to open the app!",
        "open_app": "💕 Open YourMeet",
        "get_premium": "👑 Get Premium",
        "quick_actions": "👇 Quick actions:",
        "profile_approved": "🎉 *Congratulations {name}!*\n\nYour YourMeet profile has been *approved* ✅\nYou can now start swiping and matching!\n\nTap below to find your match 💕",
        "profile_verified": "🎉 *Congratulations {name}!*\n\nYour YourMeet profile has been *approved* ✅\n⭐ Your profile is also *Verified* — badge shown on your card!\n\nTap below to find your match 💕",
        "profile_rejected": "🚫 *{name}*, your profile was rejected.\n\nPlease re-register with a clear photo and genuine bio.",
        "profile_banned": "🚫 *Your account has been permanently banned.*\n\nYou can no longer use this service.",
        "profile_pending": "⏳ *Profile under review!*\n\nAdmin will approve your profile soon. You'll get a notification once approved!",
        "match_notify": "💕 *It's a Match!*\n\nYou and *{name}* liked each other!",
        "match_contact": "\n\n📱 Contact: *{handle}*",
        "match_locked": "\n\n🔒 *Upgrade to Premium* to see contact details!",
        "start_swiping": "💕 Start Swiping",
        "view_matches": "💕 View Matches",
        "unlock_contact": "👑 Unlock Contact — Premium",
        "re_register_bot": "🤖 Re-register via Bot",
        "re_register_app": "🌐 Re-register via App",
        "daily_limit": "😔 *Daily limit reached!*\n\nUse /share to get +10 swipes or go Premium!",
        "no_super_likes": "⭐ *No super likes left today!*\n\nYou get 1 free super like per day. Come back tomorrow or go Premium!",
    },
    "es": {
        "language_select": "🌍 Por favor selecciona tu idioma:",
        "welcome": "¡Hola {name}! 👋\n\nBienvenido a *YourMeet* 💕\n\n🔥 Desliza y descubre personas\n⭐ Envía super likes\n💕 Conecta con matches\n👑 Hazte Premium para acceso ilimitado\n\n¡Toca abajo para abrir la app!",
        "open_app": "💕 Abrir YourMeet",
        "get_premium": "👑 Obtener Premium",
        "quick_actions": "👇 Acciones rápidas:",
    },
    "ru": {
        "language_select": "🌍 Пожалуйста, выберите язык:",
        "welcome": "Привет {name}! 👋\n\nДобро пожаловать в *YourMeet* 💕\n\n🔥 Свайпай и знакомься\n⭐ Отправляй супер-лайки\n💕 Находи совпадения\n👑 Получи Premium для безлимитного доступа\n\nНажми ниже, чтобы открыть приложение!",
        "open_app": "💕 Открыть YourMeet",
        "get_premium": "👑 Получить Premium",
        "quick_actions": "👇 Быстрые действия:",
    },
    "ko": {
        "language_select": "🌍 언어를 선택해주세요:",
        "welcome": "안녕하세요 {name}! 👋\n\n*YourMeet*에 오신 것을 환영합니다 💕\n\n🔥 스와이프하고 사람들을 만나세요\n⭐ 슈퍼 라이크 보내기\n💕 매칭하고 연결하기\n👑 무제한 액세스를 위한 프리미엄\n\n아래를 탭하여 앱을 여세요!",
        "open_app": "💕 YourMeet 열기",
        "get_premium": "👑 프리미엄 구매",
        "quick_actions": "👇 빠른 작업:",
    },
    "zh": {
        "language_select": "🌍 请选择您的语言：",
        "welcome": "你好 {name}！👋\n\n欢迎来到 *YourMeet* 💕\n\n🔥 滑动发现新朋友\n⭐ 发送超级喜欢\n💕 匹配并连接\n👑 升级Premium享受无限访问\n\n点击下方打开应用！",
        "open_app": "💕 打开 YourMeet",
        "get_premium": "👑 获取 Premium",
        "quick_actions": "👇 快捷操作：",
    },
    "id": {
        "language_select": "🌍 Silakan pilih bahasa Anda:",
        "welcome": "Hei {name}! 👋\n\nSelamat datang di *YourMeet* 💕\n\n🔥 Swipe & temukan orang baru\n⭐ Kirim super likes\n💕 Match & terhubung\n👑 Dapatkan Premium untuk akses tak terbatas\n\nKetuk di bawah untuk membuka aplikasi!",
        "open_app": "💕 Buka YourMeet",
        "get_premium": "👑 Dapatkan Premium",
        "quick_actions": "👇 Aksi cepat:",
    },
    "ar": {
        "language_select": "🌍 الرجاء اختيار لغتك:",
        "welcome": "مرحباً {name}! 👋\n\nأهلاً بك في *YourMeet* 💕\n\n🔥 تمرير واكتشاف أشخاص جدد\n⭐ إرسال إعجابات خاصة\n💕 التطابق والتواصل\n👑 احصل على Premium للوصول غير المحدود\n\nاضغط أدناه لفتح التطبيق!",
        "open_app": "💕 فتح YourMeet",
        "get_premium": "👑 الحصول على Premium",
        "quick_actions": "👇 إجراءات سريعة:",
    },
    "pt": {
        "language_select": "🌍 Por favor, selecione seu idioma:",
        "welcome": "Olá {name}! 👋\n\nBem-vindo ao *YourMeet* 💕\n\n🔥 Deslize e descubra pessoas\n⭐ Envie super likes\n💕 Combine e conecte\n👑 Obtenha Premium para acesso ilimitado\n\nToque abaixo para abrir o app!",
        "open_app": "💕 Abrir YourMeet",
        "get_premium": "👑 Obter Premium",
        "quick_actions": "👇 Ações rápidas:",
    },
    "fr": {
        "language_select": "🌍 Veuillez sélectionner votre langue :",
        "welcome": "Salut {name} ! 👋\n\nBienvenue sur *YourMeet* 💕\n\n🔥 Swipe et découvre des gens\n⭐ Envoie des super likes\n💕 Match et connecte-toi\n👑 Passe Premium pour un accès illimité\n\nAppuie ci-dessous pour ouvrir l'app !",
        "open_app": "💕 Ouvrir YourMeet",
        "get_premium": "👑 Obtenir Premium",
        "quick_actions": "👇 Actions rapides :",
    },
    "de": {
        "language_select": "🌍 Bitte wähle deine Sprache:",
        "welcome": "Hey {name}! 👋\n\nWillkommen bei *YourMeet* 💕\n\n🔥 Swipe & entdecke Menschen\n⭐ Sende Super-Likes\n💕 Match & verbinde dich\n👑 Hol dir Premium für unbegrenzten Zugang\n\nTippe unten, um die App zu öffnen!",
        "open_app": "💕 YourMeet öffnen",
        "get_premium": "👑 Premium holen",
        "quick_actions": "👇 Schnellaktionen:",
    },
    "hi": {
        "language_select": "🌍 कृपया अपनी भाषा चुनें:",
        "welcome": "नमस्ते {name}! 👋\n\n*YourMeet* में आपका स्वागत है 💕\n\n🔥 स्वाइप करें और लोगों से मिलें\n⭐ सुपर लाइक भेजें\n💕 मैच करें और जुड़ें\n👑 असीमित एक्सेस के लिए Premium लें\n\nऐप खोलने के लिए नीचे टैप करें!",
        "open_app": "💕 YourMeet खोलें",
        "get_premium": "👑 Premium लें",
        "quick_actions": "👇 त्वरित क्रियाएं:",
    },
    "tr": {
        "language_select": "🌍 Lütfen dilinizi seçin:",
        "welcome": "Merhaba {name}! 👋\n\n*YourMeet*'e hoş geldin 💕\n\n🔥 Kaydır ve insanları keşfet\n⭐ Süper beğeni gönder\n💕 Eşleş ve bağlan\n👑 Sınırsız erişim için Premium al\n\nUygulamayı açmak için aşağıya dokun!",
        "open_app": "💕 YourMeet'i Aç",
        "get_premium": "👑 Premium Al",
        "quick_actions": "👇 Hızlı işlemler:",
    },
    "it": {
        "language_select": "🌍 Seleziona la tua lingua:",
        "welcome": "Ciao {name}! 👋\n\nBenvenuto su *YourMeet* 💕\n\n🔥 Scorri e scopri persone\n⭐ Invia super like\n💕 Fai match e connettiti\n👑 Passa a Premium per accesso illimitato\n\nTocca qui sotto per aprire l'app!",
        "open_app": "💕 Apri YourMeet",
        "get_premium": "👑 Ottieni Premium",
        "quick_actions": "👇 Azioni rapide:",
        "profile_approved": "🎉 *Congratulazioni {name}!*\n\nIl tuo profilo YourMeet è stato *approvato* ✅\nOra puoi iniziare a fare swipe e trovare match!\n\nTocca qui sotto per trovare il tuo match 💕",
        "profile_verified": "🎉 *Congratulazioni {name}!*\n\nIl tuo profilo è stato *approvato* ✅\n⭐ Il tuo profilo è anche *Verificato*!\n\nTocca qui sotto per trovare il tuo match 💕",
        "profile_rejected": "🚫 *{name}*, il tuo profilo è stato rifiutato.\n\nRegistrati di nuovo con una foto chiara e una bio autentica.",
        "profile_banned": "🚫 *Il tuo account è stato bannato permanentemente.*",
        "match_notify": "💕 *È un Match!*\n\nTu e *{name}* vi siete piaciuti!",
        "match_contact": "\n\n📱 Contatto: *{handle}*",
        "match_locked": "\n\n🔒 *Passa a Premium* per vedere i dettagli di contatto!",
        "start_swiping": "💕 Inizia a fare Swipe",
        "view_matches": "💕 Vedi Match",
        "unlock_contact": "👑 Sblocca Contatto — Premium",
        "re_register_bot": "🤖 Registrati via Bot",
        "re_register_app": "🌐 Registrati via App",
        "daily_limit": "😔 *Limite giornaliero raggiunto!*",
        "no_super_likes": "⭐ *Nessun super like rimasto oggi!*",
    },
    "ja": {
        "language_select": "🌍 言語を選択してください:",
        "welcome": "{name}さん、こんにちは！👋\n\n*YourMeet*へようこそ 💕\n\n🔥 スワイプして人々を発見\n⭐ スーパーライクを送る\n💕 マッチして繋がる\n👑 無制限アクセスのためにプレミアムへ\n\nアプリを開くには下をタップ！",
        "open_app": "💕 YourMeetを開く",
        "get_premium": "👑 プレミアムを取得",
        "quick_actions": "👇 クイックアクション:",
        "profile_approved": "🎉 *おめでとうございます {name}!*\n\nYourMeetのプロフィールが*承認*されました ✅\nスワイプを始めましょう！\n\nマッチを見つけるには下をタップ 💕",
        "profile_verified": "🎉 *おめでとうございます {name}!*\n\nプロフィールが*承認*されました ✅\n⭐ プロフィールは*認証済み*です！\n\nマッチを見つけるには下をタップ 💕",
        "profile_rejected": "🚫 *{name}*さん、プロフィールが拒否されました。\n\n明確な写真と本物の自己紹介で再登録してください。",
        "profile_banned": "🚫 *アカウントが永久にBANされました。*",
        "match_notify": "💕 *マッチしました！*\n\nあなたと*{name}*さんがお互いに好きです！",
        "match_contact": "\n\n📱 連絡先: *{handle}*",
        "match_locked": "\n\n🔒 連絡先を見るには*プレミアム*にアップグレード！",
        "start_swiping": "💕 スワイプを始める",
        "view_matches": "💕 マッチを見る",
        "unlock_contact": "👑 連絡先を解除 — プレミアム",
        "re_register_bot": "🤖 Botで再登録",
        "re_register_app": "🌐 アプリで再登録",
        "daily_limit": "😔 *1日の上限に達しました！*",
        "no_super_likes": "⭐ *今日のスーパーライクがありません！*",
    },
}

def get(lang: str, key: str, **kwargs) -> str:
    """Get string in given language, fallback to English."""
    text = STRINGS.get(lang, STRINGS["en"]).get(key) or STRINGS["en"].get(key, key)
    return text.format(**kwargs) if kwargs else text
