STRINGS = {
    "en": {
        "welcome": "👋 Welcome to *YourMeet*!\n\nFind your perfect match from around the world. 🌍",
        "choose_language": "🌐 Please choose your language:",
        "language_set": "✅ Language set to English!",
        "open_app": "💕 Open YourMeet",
        "profile_submitted": "✅ Your profile has been submitted for review!\n\nWe'll notify you once it's approved. Usually takes a few hours.",
        "profile_approved": "🎉 *Congratulations!* Your profile has been approved!\n\nYou now have *30 free swipes per day*. Open the app and start matching! 💕",
        "profile_approved_verified": "🎉 *Congratulations!* Your profile has been approved and *verified* ⭐\n\nYou now have *30 free swipes per day*. Open the app and start matching! 💕",
        "profile_rejected": "😔 Your profile was not approved this time.\n\nYou can update your profile and resubmit. Make sure your photos are clear and bio is complete.",
        "profile_banned": "🚫 Your account has been permanently banned for violating our terms of service.",
        "match_notify": "💕 *It's a Match!*\n\nYou and *{name}* liked each other!\n\nOpen the app to connect. 🎉",
        "chat_started": "💬 *Chat started with {name}!*\n\n⏱ Duration: *{duration}*\n\nSend your messages here — they'll be forwarded directly.",
        "chat_ended": "⏰ *Chat session ended.*\n\nUpgrade to Premium for unlimited chat! 👑",
        "premium_activated": "👑 *Premium Activated!*\n\nYour premium is active until *{date}*.\n\nEnjoy unlimited swipes, super likes & more! 🚀",
        "no_profile": "❌ You don't have a profile yet. Open the app to create one!",
        "your_profile": "👤 *Your Profile*\n\n📛 Name: {name}\n🎂 Age: {age}\n⚡ Gender: {gender}\n🏙 City: {city}\n💎 Premium: {premium}\n✅ Status: {status}",
        "your_matches": "💕 You have *{count}* match(es) so far!",
        "your_stats": "📊 *Your Stats*\n\n❤️ Likes given: {given}\n💌 Likes received: {received}\n💕 Matches: {matches}\n🔥 Swipes left today: {swipes}",
        "premium_info": "👑 *YourMeet Premium*\n\n✅ Unlimited swipes\n✅ Unlimited super likes\n✅ See who liked you\n✅ Contact details on match\n✅ Profile boost (30 min)\n✅ Priority in feed\n✅ Unlimited bot chat\n\n💰 *Plans:*\n• 1 Month — 150 ⭐\n• 3 Months — 350 ⭐",
        "referral_msg": "🔗 *Your Referral Link:*\n\n{link}\n\nEvery 3 friends = +10 bonus swipes! 🎁",
        "help_msg": "❓ *Help*\n\n/profile — View your profile\n/matches — Your matches\n/stats — Your activity\n/premium — Buy premium\n/share — Referral link\n/language — Change language\n/delete — Delete account\n/about — About app",
        "about_msg": "💕 *YourMeet*\n\nA modern dating app built on Telegram.\n\n👨‍💻 Developer: @who_is_the-black_hat\n🌍 Find matches worldwide\n💬 Chat via Telegram bot\n🗺 Map discovery feature",
        "delete_confirm": "⚠️ Are you sure you want to delete your account? This cannot be undone.\n\nType /confirmdelete to confirm.",
        "account_deleted": "✅ Your account has been deleted. Sorry to see you go!",
        "boost_active": "🚀 *Profile Boosted!*\n\nYour profile will be shown first for the next 30 minutes!",
        "language_changed": "✅ Language updated!",
        "not_approved_yet": "⏳ Your profile is still under review. We'll notify you soon!",
    },

    "es": {
        "welcome": "👋 ¡Bienvenido a *YourMeet*!\n\nEncuentra tu pareja perfecta de todo el mundo. 🌍",
        "choose_language": "🌐 Por favor elige tu idioma:",
        "language_set": "✅ ¡Idioma configurado en Español!",
        "open_app": "💕 Abrir YourMeet",
        "profile_submitted": "✅ ¡Tu perfil ha sido enviado para revisión!\n\nTe notificaremos cuando sea aprobado. Generalmente tarda unas horas.",
        "profile_approved": "🎉 ¡*Felicitaciones!* ¡Tu perfil ha sido aprobado!\n\nAhora tienes *30 swipes gratis por día*. ¡Abre la app y empieza a hacer matches! 💕",
        "profile_approved_verified": "🎉 ¡*Felicitaciones!* Tu perfil fue aprobado y *verificado* ⭐\n\nAhora tienes *30 swipes gratis por día*. ¡Abre la app! 💕",
        "profile_rejected": "😔 Tu perfil no fue aprobado esta vez.\n\nPuedes actualizar tu perfil y volver a enviarlo.",
        "profile_banned": "🚫 Tu cuenta ha sido baneada permanentemente por violar nuestros términos.",
        "match_notify": "💕 *¡Es un Match!*\n\n¡Tú y *{name}* se gustaron mutuamente!\n\nAbre la app para conectar. 🎉",
        "chat_started": "💬 *¡Chat iniciado con {name}!*\n\n⏱ Duración: *{duration}*\n\nEnvía tus mensajes aquí.",
        "chat_ended": "⏰ *Sesión de chat terminada.*\n\n¡Actualiza a Premium para chat ilimitado! 👑",
        "premium_activated": "👑 *¡Premium Activado!*\n\nTu premium está activo hasta *{date}*. 🚀",
        "no_profile": "❌ Aún no tienes perfil. ¡Abre la app para crear uno!",
        "your_profile": "👤 *Tu Perfil*\n\n📛 Nombre: {name}\n🎂 Edad: {age}\n⚡ Género: {gender}\n🏙 Ciudad: {city}\n💎 Premium: {premium}\n✅ Estado: {status}",
        "your_matches": "💕 Tienes *{count}* match(es) hasta ahora!",
        "your_stats": "📊 *Tus Estadísticas*\n\n❤️ Likes dados: {given}\n💌 Likes recibidos: {received}\n💕 Matches: {matches}\n🔥 Swipes restantes hoy: {swipes}",
        "premium_info": "👑 *YourMeet Premium*\n\n✅ Swipes ilimitados\n✅ Super likes ilimitados\n✅ Ver quién te gustó\n✅ Contacto en match\n✅ Boost de perfil\n✅ Prioridad en feed\n✅ Chat ilimitado\n\n💰 *Planes:*\n• 1 Mes — 150 ⭐\n• 3 Meses — 350 ⭐",
        "referral_msg": "🔗 *Tu Link de Referido:*\n\n{link}\n\n¡Cada 3 amigos = +10 swipes bonus! 🎁",
        "help_msg": "❓ *Ayuda*\n\n/profile — Ver tu perfil\n/matches — Tus matches\n/stats — Tu actividad\n/premium — Comprar premium\n/share — Link de referido\n/language — Cambiar idioma\n/delete — Eliminar cuenta\n/about — Sobre la app",
        "about_msg": "💕 *YourMeet*\n\nUna app de citas moderna en Telegram.\n\n👨‍💻 Desarrollador: @who_is_the-black_hat",
        "delete_confirm": "⚠️ ¿Estás seguro de que quieres eliminar tu cuenta?\n\nEscribe /confirmdelete para confirmar.",
        "account_deleted": "✅ Tu cuenta ha sido eliminada. ¡Hasta pronto!",
        "boost_active": "🚀 *¡Perfil Impulsado!*\n\n¡Tu perfil se mostrará primero durante los próximos 30 minutos!",
        "language_changed": "✅ ¡Idioma actualizado!",
        "not_approved_yet": "⏳ Tu perfil aún está en revisión. ¡Te notificaremos pronto!",
    },

    "ru": {
        "welcome": "👋 Добро пожаловать в *YourMeet*!\n\nНайди свою идеальную пару со всего мира. 🌍",
        "choose_language": "🌐 Пожалуйста, выберите язык:",
        "language_set": "✅ Язык установлен: Русский!",
        "open_app": "💕 Открыть YourMeet",
        "profile_submitted": "✅ Ваш профиль отправлен на проверку!\n\nМы уведомим вас после одобрения. Обычно занимает несколько часов.",
        "profile_approved": "🎉 *Поздравляем!* Ваш профиль одобрен!\n\nТеперь у вас *30 бесплатных свайпов в день*. Открывайте приложение! 💕",
        "profile_approved_verified": "🎉 *Поздравляем!* Ваш профиль одобрен и *верифицирован* ⭐\n\nТеперь у вас *30 бесплатных свайпов в день*. 💕",
        "profile_rejected": "😔 Ваш профиль не был одобрен.\n\nВы можете обновить профиль и отправить снова.",
        "profile_banned": "🚫 Ваш аккаунт заблокирован навсегда за нарушение правил.",
        "match_notify": "💕 *Это Мэтч!*\n\nВы и *{name}* понравились друг другу!\n\nОткройте приложение. 🎉",
        "chat_started": "💬 *Чат начат с {name}!*\n\n⏱ Длительность: *{duration}*\n\nОтправляйте сообщения здесь.",
        "chat_ended": "⏰ *Сессия чата завершена.*\n\nОформите Premium для безлимитного чата! 👑",
        "premium_activated": "👑 *Premium активирован!*\n\nВаш premium активен до *{date}*. 🚀",
        "no_profile": "❌ У вас ещё нет профиля. Откройте приложение!",
        "your_profile": "👤 *Ваш Профиль*\n\n📛 Имя: {name}\n🎂 Возраст: {age}\n⚡ Пол: {gender}\n🏙 Город: {city}\n💎 Premium: {premium}\n✅ Статус: {status}",
        "your_matches": "💕 У вас *{count}* мэтч(ей)!",
        "your_stats": "📊 *Ваша Статистика*\n\n❤️ Лайков отдано: {given}\n💌 Лайков получено: {received}\n💕 Мэтчей: {matches}\n🔥 Свайпов сегодня: {swipes}",
        "premium_info": "👑 *YourMeet Premium*\n\n✅ Безлимитные свайпы\n✅ Безлимитные супер-лайки\n✅ Кто вас лайкнул\n✅ Контакты при мэтче\n✅ Буст профиля\n✅ Приоритет в ленте\n✅ Безлимитный чат\n\n💰 *Планы:*\n• 1 Месяц — 150 ⭐\n• 3 Месяца — 350 ⭐",
        "referral_msg": "🔗 *Ваша реферальная ссылка:*\n\n{link}\n\nКаждые 3 друга = +10 свайпов! 🎁",
        "help_msg": "❓ *Помощь*\n\n/profile — Ваш профиль\n/matches — Ваши мэтчи\n/stats — Статистика\n/premium — Купить premium\n/share — Реферальная ссылка\n/language — Сменить язык\n/delete — Удалить аккаунт\n/about — О приложении",
        "about_msg": "💕 *YourMeet*\n\nСовременное приложение для знакомств в Telegram.\n\n👨‍💻 Разработчик: @who_is_the-black_hat",
        "delete_confirm": "⚠️ Вы уверены, что хотите удалить аккаунт?\n\nНапишите /confirmdelete для подтверждения.",
        "account_deleted": "✅ Ваш аккаунт удалён. До свидания!",
        "boost_active": "🚀 *Профиль продвинут!*\n\nВаш профиль будет показываться первым 30 минут!",
        "language_changed": "✅ Язык обновлён!",
        "not_approved_yet": "⏳ Ваш профиль ещё на проверке. Скоро уведомим!",
    },

    "ko": {
        "welcome": "👋 *YourMeet*에 오신 것을 환영합니다!\n\n전 세계에서 완벽한 파트너를 찾아보세요. 🌍",
        "choose_language": "🌐 언어를 선택해 주세요:",
        "language_set": "✅ 언어가 한국어로 설정되었습니다!",
        "open_app": "💕 YourMeet 열기",
        "profile_submitted": "✅ 프로필이 검토를 위해 제출되었습니다!\n\n승인되면 알려드리겠습니다. 보통 몇 시간이 걸립니다.",
        "profile_approved": "🎉 *축하합니다!* 프로필이 승인되었습니다!\n\n하루 *30번의 무료 스와이프*가 제공됩니다. 앱을 열고 매칭을 시작하세요! 💕",
        "profile_approved_verified": "🎉 *축하합니다!* 프로필이 승인 및 *인증*되었습니다 ⭐\n\n하루 *30번의 무료 스와이프*가 제공됩니다. 💕",
        "profile_rejected": "😔 이번에는 프로필이 승인되지 않았습니다.\n\n프로필을 업데이트하고 다시 제출할 수 있습니다.",
        "profile_banned": "🚫 이용약관 위반으로 계정이 영구 정지되었습니다.",
        "match_notify": "💕 *매칭되었습니다!*\n\n당신과 *{name}*이 서로 좋아했습니다!\n\n앱을 열어 연결하세요. 🎉",
        "chat_started": "💬 *{name}과의 채팅이 시작되었습니다!*\n\n⏱ 시간: *{duration}*\n\n여기에 메시지를 보내세요.",
        "chat_ended": "⏰ *채팅 세션이 종료되었습니다.*\n\n무제한 채팅을 위해 프리미엄으로 업그레이드하세요! 👑",
        "premium_activated": "👑 *프리미엄 활성화!*\n\n프리미엄이 *{date}*까지 활성화됩니다. 🚀",
        "no_profile": "❌ 아직 프로필이 없습니다. 앱을 열어 만들어보세요!",
        "your_profile": "👤 *내 프로필*\n\n📛 이름: {name}\n🎂 나이: {age}\n⚡ 성별: {gender}\n🏙 도시: {city}\n💎 프리미엄: {premium}\n✅ 상태: {status}",
        "your_matches": "💕 현재 *{count}*개의 매칭이 있습니다!",
        "your_stats": "📊 *내 통계*\n\n❤️ 준 좋아요: {given}\n💌 받은 좋아요: {received}\n💕 매칭: {matches}\n🔥 오늘 남은 스와이프: {swipes}",
        "premium_info": "👑 *YourMeet 프리미엄*\n\n✅ 무제한 스와이프\n✅ 무제한 슈퍼 좋아요\n✅ 나를 좋아한 사람 보기\n✅ 매칭 시 연락처\n✅ 프로필 부스트\n✅ 피드 우선순위\n✅ 무제한 채팅\n\n💰 *요금제:*\n• 1개월 — 150 ⭐\n• 3개월 — 350 ⭐",
        "referral_msg": "🔗 *내 추천 링크:*\n\n{link}\n\n친구 3명마다 = +10 스와이프 보너스! 🎁",
        "help_msg": "❓ *도움말*\n\n/profile — 내 프로필\n/matches — 내 매칭\n/stats — 활동 통계\n/premium — 프리미엄 구매\n/share — 추천 링크\n/language — 언어 변경\n/delete — 계정 삭제\n/about — 앱 정보",
        "about_msg": "💕 *YourMeet*\n\nTelegram 기반 현대적인 데이팅 앱.\n\n👨💻 개발자: @who_is_the-black_hat",
        "delete_confirm": "⚠️ 정말로 계정을 삭제하시겠습니까?\n\n확인하려면 /confirmdelete를 입력하세요.",
        "account_deleted": "✅ 계정이 삭제되었습니다. 안녕히 가세요!",
        "boost_active": "🚀 *프로필 부스트!*\n\n30분 동안 프로필이 먼저 표시됩니다!",
        "language_changed": "✅ 언어가 업데이트되었습니다!",
        "not_approved_yet": "⏳ 프로필이 아직 검토 중입니다. 곧 알려드리겠습니다!",
    },

    "zh": {
        "welcome": "👋 欢迎来到 *YourMeet*！\n\n在全球寻找你的完美伴侣。🌍",
        "choose_language": "🌐 请选择您的语言：",
        "language_set": "✅ 语言已设置为中文！",
        "open_app": "💕 打开 YourMeet",
        "profile_submitted": "✅ 您的资料已提交审核！\n\n审核通过后我们会通知您，通常需要几个小时。",
        "profile_approved": "🎉 *恭喜！* 您的资料已通过审核！\n\n您现在每天有 *30次免费滑动*。打开应用开始匹配吧！💕",
        "profile_approved_verified": "🎉 *恭喜！* 您的资料已通过审核并获得*认证* ⭐\n\n每天 *30次免费滑动*。💕",
        "profile_rejected": "😔 您的资料这次未获批准。\n\n您可以更新资料后重新提交。",
        "profile_banned": "🚫 您的账户因违反服务条款已被永久封禁。",
        "match_notify": "💕 *匹配成功！*\n\n您和 *{name}* 互相喜欢！\n\n打开应用联系对方。🎉",
        "chat_started": "💬 *与 {name} 的聊天已开始！*\n\n⏱ 时长：*{duration}*\n\n在这里发送消息。",
        "chat_ended": "⏰ *聊天会话已结束。*\n\n升级到高级版享受无限聊天！👑",
        "premium_activated": "👑 *高级版已激活！*\n\n您的高级版有效期至 *{date}*。🚀",
        "no_profile": "❌ 您还没有资料。打开应用创建一个吧！",
        "your_profile": "👤 *我的资料*\n\n📛 姓名：{name}\n🎂 年龄：{age}\n⚡ 性别：{gender}\n🏙 城市：{city}\n💎 高级版：{premium}\n✅ 状态：{status}",
        "your_matches": "💕 您目前有 *{count}* 个匹配！",
        "your_stats": "📊 *我的统计*\n\n❤️ 发出的喜欢：{given}\n💌 收到的喜欢：{received}\n💕 匹配数：{matches}\n🔥 今日剩余滑动：{swipes}",
        "premium_info": "👑 *YourMeet 高级版*\n\n✅ 无限滑动\n✅ 无限超级喜欢\n✅ 查看谁喜欢了你\n✅ 匹配时显示联系方式\n✅ 资料加速\n✅ 优先展示\n✅ 无限聊天\n\n💰 *套餐：*\n• 1个月 — 150 ⭐\n• 3个月 — 350 ⭐",
        "referral_msg": "🔗 *您的推荐链接：*\n\n{link}\n\n每邀请3位朋友 = +10次滑动奖励！🎁",
        "help_msg": "❓ *帮助*\n\n/profile — 查看资料\n/matches — 我的匹配\n/stats — 活动统计\n/premium — 购买高级版\n/share — 推荐链接\n/language — 更改语言\n/delete — 删除账户\n/about — 关于应用",
        "about_msg": "💕 *YourMeet*\n\n基于 Telegram 的现代交友应用。\n\n👨💻 开发者：@who_is_the-black_hat",
        "delete_confirm": "⚠️ 您确定要删除账户吗？此操作无法撤销。\n\n输入 /confirmdelete 确认。",
        "account_deleted": "✅ 您的账户已删除。再见！",
        "boost_active": "🚀 *资料已加速！*\n\n您的资料将在接下来30分钟内优先显示！",
        "language_changed": "✅ 语言已更新！",
        "not_approved_yet": "⏳ 您的资料仍在审核中，我们会尽快通知您！",
    },

    "id": {
        "welcome": "👋 Selamat datang di *YourMeet*!\n\nTemukan pasangan sempurnamu dari seluruh dunia. 🌍",
        "choose_language": "🌐 Silakan pilih bahasa Anda:",
        "language_set": "✅ Bahasa diatur ke Bahasa Indonesia!",
        "open_app": "💕 Buka YourMeet",
        "profile_submitted": "✅ Profil kamu telah dikirim untuk ditinjau!\n\nKami akan memberi tahu kamu setelah disetujui. Biasanya membutuhkan beberapa jam.",
        "profile_approved": "🎉 *Selamat!* Profil kamu telah disetujui!\n\nKamu sekarang memiliki *30 swipe gratis per hari*. Buka aplikasi dan mulai matching! 💕",
        "profile_approved_verified": "🎉 *Selamat!* Profil kamu disetujui dan *terverifikasi* ⭐\n\n*30 swipe gratis per hari*. 💕",
        "profile_rejected": "😔 Profil kamu tidak disetujui kali ini.\n\nKamu bisa memperbarui profil dan mengirim ulang.",
        "profile_banned": "🚫 Akun kamu telah diblokir permanen karena melanggar ketentuan layanan.",
        "match_notify": "💕 *Ini Match!*\n\nKamu dan *{name}* saling menyukai!\n\nBuka aplikasi untuk terhubung. 🎉",
        "chat_started": "💬 *Chat dimulai dengan {name}!*\n\n⏱ Durasi: *{duration}*\n\nKirim pesanmu di sini.",
        "chat_ended": "⏰ *Sesi chat telah berakhir.*\n\nUpgrade ke Premium untuk chat tanpa batas! 👑",
        "premium_activated": "👑 *Premium Diaktifkan!*\n\nPremium kamu aktif hingga *{date}*. 🚀",
        "no_profile": "❌ Kamu belum punya profil. Buka aplikasi untuk membuatnya!",
        "your_profile": "👤 *Profil Kamu*\n\n📛 Nama: {name}\n🎂 Usia: {age}\n⚡ Gender: {gender}\n🏙 Kota: {city}\n💎 Premium: {premium}\n✅ Status: {status}",
        "your_matches": "💕 Kamu punya *{count}* match sejauh ini!",
        "your_stats": "📊 *Statistik Kamu*\n\n❤️ Like diberikan: {given}\n💌 Like diterima: {received}\n💕 Match: {matches}\n🔥 Swipe tersisa hari ini: {swipes}",
        "premium_info": "👑 *YourMeet Premium*\n\n✅ Swipe tanpa batas\n✅ Super like tanpa batas\n✅ Lihat siapa yang menyukaimu\n✅ Kontak saat match\n✅ Boost profil\n✅ Prioritas di feed\n✅ Chat tanpa batas\n\n💰 *Paket:*\n• 1 Bulan — 150 ⭐\n• 3 Bulan — 350 ⭐",
        "referral_msg": "🔗 *Link Referral Kamu:*\n\n{link}\n\nSetiap 3 teman = +10 swipe bonus! 🎁",
        "help_msg": "❓ *Bantuan*\n\n/profile — Lihat profil\n/matches — Match kamu\n/stats — Statistik aktivitas\n/premium — Beli premium\n/share — Link referral\n/language — Ganti bahasa\n/delete — Hapus akun\n/about — Tentang aplikasi",
        "about_msg": "💕 *YourMeet*\n\nAplikasi kencan modern berbasis Telegram.\n\n👨💻 Developer: @who_is_the-black_hat",
        "delete_confirm": "⚠️ Apakah kamu yakin ingin menghapus akun? Ini tidak bisa dibatalkan.\n\nKetik /confirmdelete untuk konfirmasi.",
        "account_deleted": "✅ Akun kamu telah dihapus. Sampai jumpa!",
        "boost_active": "🚀 *Profil Diboost!*\n\nProfilmu akan ditampilkan pertama selama 30 menit ke depan!",
        "language_changed": "✅ Bahasa diperbarui!",
        "not_approved_yet": "⏳ Profil kamu masih dalam peninjauan. Kami akan segera memberi tahu!",
    },

    "ar": {
        "welcome": "👋 مرحباً بك في *YourMeet*!\n\nابحث عن شريك حياتك المثالي من جميع أنحاء العالم. 🌍",
        "choose_language": "🌐 يرجى اختيار لغتك:",
        "language_set": "✅ تم تعيين اللغة إلى العربية!",
        "open_app": "💕 فتح YourMeet",
        "profile_submitted": "✅ تم إرسال ملفك الشخصي للمراجعة!\n\nسنخطرك عند الموافقة عليه. عادةً ما يستغرق بضع ساعات.",
        "profile_approved": "🎉 *تهانينا!* تمت الموافقة على ملفك الشخصي!\n\nلديك الآن *30 سحبة مجانية يومياً*. افتح التطبيق وابدأ المطابقة! 💕",
        "profile_approved_verified": "🎉 *تهانينا!* تمت الموافقة على ملفك وتم *التحقق منه* ⭐\n\n*30 سحبة مجانية يومياً*. 💕",
        "profile_rejected": "😔 لم تتم الموافقة على ملفك الشخصي هذه المرة.\n\nيمكنك تحديث ملفك وإعادة الإرسال.",
        "profile_banned": "🚫 تم حظر حسابك بشكل دائم لانتهاك شروط الخدمة.",
        "match_notify": "💕 *إنه تطابق!*\n\nأنت و*{name}* أحببتما بعضكما!\n\nافتح التطبيق للتواصل. 🎉",
        "chat_started": "💬 *بدأت المحادثة مع {name}!*\n\n⏱ المدة: *{duration}*\n\nأرسل رسائلك هنا.",
        "chat_ended": "⏰ *انتهت جلسة المحادثة.*\n\nرقّ إلى Premium للمحادثة غير المحدودة! 👑",
        "premium_activated": "👑 *تم تفعيل Premium!*\n\nاشتراكك نشط حتى *{date}*. 🚀",
        "no_profile": "❌ ليس لديك ملف شخصي بعد. افتح التطبيق لإنشاء واحد!",
        "your_profile": "👤 *ملفك الشخصي*\n\n📛 الاسم: {name}\n🎂 العمر: {age}\n⚡ الجنس: {gender}\n🏙 المدينة: {city}\n💎 Premium: {premium}\n✅ الحالة: {status}",
        "your_matches": "💕 لديك *{count}* تطابق حتى الآن!",
        "your_stats": "📊 *إحصائياتك*\n\n❤️ الإعجابات المُرسلة: {given}\n💌 الإعجابات المُستلمة: {received}\n💕 التطابقات: {matches}\n🔥 السحبات المتبقية اليوم: {swipes}",
        "premium_info": "👑 *YourMeet Premium*\n\n✅ سحبات غير محدودة\n✅ إعجابات خارقة غير محدودة\n✅ رؤية من أعجب بك\n✅ معلومات الاتصال عند التطابق\n✅ تعزيز الملف الشخصي\n✅ الأولوية في الخلاصة\n✅ محادثة غير محدودة\n\n💰 *الخطط:*\n• شهر واحد — 150 ⭐\n• 3 أشهر — 350 ⭐",
        "referral_msg": "🔗 *رابط الإحالة الخاص بك:*\n\n{link}\n\nكل 3 أصدقاء = +10 سحبات مكافأة! 🎁",
        "help_msg": "❓ *المساعدة*\n\n/profile — عرض ملفك\n/matches — تطابقاتك\n/stats — إحصائيات النشاط\n/premium — شراء Premium\n/share — رابط الإحالة\n/language — تغيير اللغة\n/delete — حذف الحساب\n/about — حول التطبيق",
        "about_msg": "💕 *YourMeet*\n\nتطبيق مواعدة حديث مبني على Telegram.\n\n👨💻 المطور: @who_is_the-black_hat",
        "delete_confirm": "⚠️ هل أنت متأكد أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا.\n\nاكتب /confirmdelete للتأكيد.",
        "account_deleted": "✅ تم حذف حسابك. إلى اللقاء!",
        "boost_active": "🚀 *تم تعزيز الملف الشخصي!*\n\nسيظهر ملفك أولاً خلال الـ 30 دقيقة القادمة!",
        "language_changed": "✅ تم تحديث اللغة!",
        "not_approved_yet": "⏳ ملفك الشخصي لا يزال قيد المراجعة. سنخطرك قريباً!",
    },

    "pt": {
        "welcome": "👋 Bem-vindo ao *YourMeet*!\n\nEncontre seu par perfeito de todo o mundo. 🌍",
        "choose_language": "🌐 Por favor, escolha seu idioma:",
        "language_set": "✅ Idioma definido para Português!",
        "open_app": "💕 Abrir YourMeet",
        "profile_submitted": "✅ Seu perfil foi enviado para revisão!\n\nVamos notificá-lo quando for aprovado. Geralmente leva algumas horas.",
        "profile_approved": "🎉 *Parabéns!* Seu perfil foi aprovado!\n\nVocê tem *30 swipes gratuitos por dia*. Abra o app e comece a fazer matches! 💕",
        "profile_approved_verified": "🎉 *Parabéns!* Seu perfil foi aprovado e *verificado* ⭐\n\n*30 swipes gratuitos por dia*. 💕",
        "profile_rejected": "😔 Seu perfil não foi aprovado desta vez.\n\nVocê pode atualizar seu perfil e reenviar.",
        "profile_banned": "🚫 Sua conta foi banida permanentemente por violar nossos termos.",
        "match_notify": "💕 *É um Match!*\n\nVocê e *{name}* se curtiram!\n\nAbra o app para se conectar. 🎉",
        "chat_started": "💬 *Chat iniciado com {name}!*\n\n⏱ Duração: *{duration}*\n\nEnvie suas mensagens aqui.",
        "chat_ended": "⏰ *Sessão de chat encerrada.*\n\nAtualize para Premium para chat ilimitado! 👑",
        "premium_activated": "👑 *Premium Ativado!*\n\nSeu premium está ativo até *{date}*. 🚀",
        "no_profile": "❌ Você ainda não tem perfil. Abra o app para criar um!",
        "your_profile": "👤 *Seu Perfil*\n\n📛 Nome: {name}\n🎂 Idade: {age}\n⚡ Gênero: {gender}\n🏙 Cidade: {city}\n💎 Premium: {premium}\n✅ Status: {status}",
        "your_matches": "💕 Você tem *{count}* match(es) até agora!",
        "your_stats": "📊 *Suas Estatísticas*\n\n❤️ Likes dados: {given}\n💌 Likes recebidos: {received}\n💕 Matches: {matches}\n🔥 Swipes restantes hoje: {swipes}",
        "premium_info": "👑 *YourMeet Premium*\n\n✅ Swipes ilimitados\n✅ Super likes ilimitados\n✅ Ver quem te curtiu\n✅ Contato no match\n✅ Boost de perfil\n✅ Prioridade no feed\n✅ Chat ilimitado\n\n💰 *Planos:*\n• 1 Mês — 150 ⭐\n• 3 Meses — 350 ⭐",
        "referral_msg": "🔗 *Seu Link de Indicação:*\n\n{link}\n\nCada 3 amigos = +10 swipes bônus! 🎁",
        "help_msg": "❓ *Ajuda*\n\n/profile — Ver perfil\n/matches — Seus matches\n/stats — Estatísticas\n/premium — Comprar premium\n/share — Link de indicação\n/language — Mudar idioma\n/delete — Excluir conta\n/about — Sobre o app",
        "about_msg": "💕 *YourMeet*\n\nUm app de namoro moderno no Telegram.\n\n👨💻 Desenvolvedor: @who_is_the-black_hat",
        "delete_confirm": "⚠️ Tem certeza que quer excluir sua conta?\n\nDigite /confirmdelete para confirmar.",
        "account_deleted": "✅ Sua conta foi excluída. Até logo!",
        "boost_active": "🚀 *Perfil Impulsionado!*\n\nSeu perfil será mostrado primeiro pelos próximos 30 minutos!",
        "language_changed": "✅ Idioma atualizado!",
        "not_approved_yet": "⏳ Seu perfil ainda está em análise. Avisaremos em breve!",
    },

    "fr": {
        "welcome": "👋 Bienvenue sur *YourMeet*!\n\nTrouvez votre partenaire idéal dans le monde entier. 🌍",
        "choose_language": "🌐 Veuillez choisir votre langue:",
        "language_set": "✅ Langue définie sur Français!",
        "open_app": "💕 Ouvrir YourMeet",
        "profile_submitted": "✅ Votre profil a été soumis pour examen!\n\nNous vous notifierons une fois approuvé. Cela prend généralement quelques heures.",
        "profile_approved": "🎉 *Félicitations!* Votre profil a été approuvé!\n\nVous avez maintenant *30 swipes gratuits par jour*. Ouvrez l'app et commencez à matcher! 💕",
        "profile_approved_verified": "🎉 *Félicitations!* Votre profil est approuvé et *vérifié* ⭐\n\n*30 swipes gratuits par jour*. 💕",
        "profile_rejected": "😔 Votre profil n'a pas été approuvé cette fois.\n\nVous pouvez mettre à jour votre profil et le soumettre à nouveau.",
        "profile_banned": "🚫 Votre compte a été banni définitivement pour violation de nos conditions.",
        "match_notify": "💕 *C'est un Match!*\n\nVous et *{name}* vous êtes mutuellement aimés!\n\nOuvrez l'app pour vous connecter. 🎉",
        "chat_started": "💬 *Chat démarré avec {name}!*\n\n⏱ Durée: *{duration}*\n\nEnvoyez vos messages ici.",
        "chat_ended": "⏰ *Session de chat terminée.*\n\nPassez à Premium pour un chat illimité! 👑",
        "premium_activated": "👑 *Premium Activé!*\n\nVotre premium est actif jusqu'au *{date}*. 🚀",
        "no_profile": "❌ Vous n'avez pas encore de profil. Ouvrez l'app pour en créer un!",
        "your_profile": "👤 *Votre Profil*\n\n📛 Nom: {name}\n🎂 Âge: {age}\n⚡ Genre: {gender}\n🏙 Ville: {city}\n💎 Premium: {premium}\n✅ Statut: {status}",
        "your_matches": "💕 Vous avez *{count}* match(es) jusqu'à présent!",
        "your_stats": "📊 *Vos Statistiques*\n\n❤️ Likes donnés: {given}\n💌 Likes reçus: {received}\n💕 Matches: {matches}\n🔥 Swipes restants aujourd'hui: {swipes}",
        "premium_info": "👑 *YourMeet Premium*\n\n✅ Swipes illimités\n✅ Super likes illimités\n✅ Voir qui vous a aimé\n✅ Contact lors du match\n✅ Boost de profil\n✅ Priorité dans le feed\n✅ Chat illimité\n\n💰 *Plans:*\n• 1 Mois — 150 ⭐\n• 3 Mois — 350 ⭐",
        "referral_msg": "🔗 *Votre Lien de Parrainage:*\n\n{link}\n\nChaque 3 amis = +10 swipes bonus! 🎁",
        "help_msg": "❓ *Aide*\n\n/profile — Voir profil\n/matches — Vos matches\n/stats — Statistiques\n/premium — Acheter premium\n/share — Lien de parrainage\n/language — Changer la langue\n/delete — Supprimer le compte\n/about — À propos",
        "about_msg": "💕 *YourMeet*\n\nUne app de rencontres moderne sur Telegram.\n\n👨💻 Développeur: @who_is_the-black_hat",
        "delete_confirm": "⚠️ Êtes-vous sûr de vouloir supprimer votre compte?\n\nTapez /confirmdelete pour confirmer.",
        "account_deleted": "✅ Votre compte a été supprimé. Au revoir!",
        "boost_active": "🚀 *Profil Boosté!*\n\nVotre profil sera affiché en premier pendant les 30 prochaines minutes!",
        "language_changed": "✅ Langue mise à jour!",
        "not_approved_yet": "⏳ Votre profil est encore en cours d'examen. Nous vous notifierons bientôt!",
    },

    "de": {
        "welcome": "👋 Willkommen bei *YourMeet*!\n\nFinde deinen perfekten Partner aus aller Welt. 🌍",
        "choose_language": "🌐 Bitte wähle deine Sprache:",
        "language_set": "✅ Sprache auf Deutsch eingestellt!",
        "open_app": "💕 YourMeet öffnen",
        "profile_submitted": "✅ Dein Profil wurde zur Überprüfung eingereicht!\n\nWir benachrichtigen dich nach der Genehmigung. Dauert normalerweise ein paar Stunden.",
        "profile_approved": "🎉 *Glückwunsch!* Dein Profil wurde genehmigt!\n\nDu hast jetzt *30 kostenlose Swipes pro Tag*. Öffne die App und fang an zu matchen! 💕",
        "profile_approved_verified": "🎉 *Glückwunsch!* Dein Profil wurde genehmigt und *verifiziert* ⭐\n\n*30 kostenlose Swipes pro Tag*. 💕",
        "profile_rejected": "😔 Dein Profil wurde diesmal nicht genehmigt.\n\nDu kannst dein Profil aktualisieren und erneut einreichen.",
        "profile_banned": "🚫 Dein Konto wurde wegen Verstoßes gegen unsere Nutzungsbedingungen dauerhaft gesperrt.",
        "match_notify": "💕 *Es ist ein Match!*\n\nDu und *{name}* habt euch gegenseitig gemocht!\n\nÖffne die App, um dich zu verbinden. 🎉",
        "chat_started": "💬 *Chat mit {name} gestartet!*\n\n⏱ Dauer: *{duration}*\n\nSende deine Nachrichten hier.",
        "chat_ended": "⏰ *Chat-Sitzung beendet.*\n\nUpgrade auf Premium für unbegrenzten Chat! 👑",
        "premium_activated": "👑 *Premium aktiviert!*\n\nDein Premium ist aktiv bis *{date}*. 🚀",
        "no_profile": "❌ Du hast noch kein Profil. Öffne die App, um eines zu erstellen!",
        "your_profile": "👤 *Dein Profil*\n\n📛 Name: {name}\n🎂 Alter: {age}\n⚡ Geschlecht: {gender}\n🏙 Stadt: {city}\n💎 Premium: {premium}\n✅ Status: {status}",
        "your_matches": "💕 Du hast bisher *{count}* Match(es)!",
        "your_stats": "📊 *Deine Statistiken*\n\n❤️ Gegebene Likes: {given}\n💌 Erhaltene Likes: {received}\n💕 Matches: {matches}\n🔥 Verbleibende Swipes heute: {swipes}",
        "premium_info": "👑 *YourMeet Premium*\n\n✅ Unbegrenzte Swipes\n✅ Unbegrenzte Super-Likes\n✅ Sehen, wer dich gemocht hat\n✅ Kontakt beim Match\n✅ Profil-Boost\n✅ Priorität im Feed\n✅ Unbegrenzter Chat\n\n💰 *Pläne:*\n• 1 Monat — 150 ⭐\n• 3 Monate — 350 ⭐",
        "referral_msg": "🔗 *Dein Empfehlungslink:*\n\n{link}\n\nJe 3 Freunde = +10 Bonus-Swipes! 🎁",
        "help_msg": "❓ *Hilfe*\n\n/profile — Profil anzeigen\n/matches — Deine Matches\n/stats — Aktivitätsstatistiken\n/premium — Premium kaufen\n/share — Empfehlungslink\n/language — Sprache ändern\n/delete — Konto löschen\n/about — Über die App",
        "about_msg": "💕 *YourMeet*\n\nEine moderne Dating-App auf Telegram.\n\n👨💻 Entwickler: @who_is_the-black_hat",
        "delete_confirm": "⚠️ Bist du sicher, dass du dein Konto löschen möchtest?\n\nGib /confirmdelete zur Bestätigung ein.",
        "account_deleted": "✅ Dein Konto wurde gelöscht. Auf Wiedersehen!",
        "boost_active": "🚀 *Profil geboostet!*\n\nDein Profil wird in den nächsten 30 Minuten zuerst angezeigt!",
        "language_changed": "✅ Sprache aktualisiert!",
        "not_approved_yet": "⏳ Dein Profil wird noch überprüft. Wir benachrichtigen dich bald!",
    },

    "tr": {
        "welcome": "👋 *YourMeet*'e Hoş Geldiniz!\n\nDünyanın dört bir yanından mükemmel eşinizi bulun. 🌍",
        "choose_language": "🌐 Lütfen dilinizi seçin:",
        "language_set": "✅ Dil Türkçe olarak ayarlandı!",
        "open_app": "💕 YourMeet'i Aç",
        "profile_submitted": "✅ Profiliniz inceleme için gönderildi!\n\nOnaylandığında sizi bilgilendireceğiz. Genellikle birkaç saat sürer.",
        "profile_approved": "🎉 *Tebrikler!* Profiliniz onaylandı!\n\nArtık günde *30 ücretsiz swipe* hakkınız var. Uygulamayı açın ve eşleşmeye başlayın! 💕",
        "profile_approved_verified": "🎉 *Tebrikler!* Profiliniz onaylandı ve *doğrulandı* ⭐\n\nGünde *30 ücretsiz swipe*. 💕",
        "profile_rejected": "😔 Profiliniz bu sefer onaylanmadı.\n\nProfilinizi güncelleyip tekrar gönderebilirsiniz.",
        "profile_banned": "🚫 Hesabınız hizmet şartlarını ihlal ettiği için kalıcı olarak yasaklandı.",
        "match_notify": "💕 *Eşleşme!*\n\nSiz ve *{name}* birbirinizi beğendiniz!\n\nBağlanmak için uygulamayı açın. 🎉",
        "chat_started": "💬 *{name} ile sohbet başladı!*\n\n⏱ Süre: *{duration}*\n\nMesajlarınızı buraya gönderin.",
        "chat_ended": "⏰ *Sohbet oturumu sona erdi.*\n\nSınırsız sohbet için Premium'a yükseltin! 👑",
        "premium_activated": "👑 *Premium Etkinleştirildi!*\n\nPremium'unuz *{date}* tarihine kadar aktif. 🚀",
        "no_profile": "❌ Henüz profiliniz yok. Oluşturmak için uygulamayı açın!",
        "your_profile": "👤 *Profiliniz*\n\n📛 Ad: {name}\n🎂 Yaş: {age}\n⚡ Cinsiyet: {gender}\n🏙 Şehir: {city}\n💎 Premium: {premium}\n✅ Durum: {status}",
        "your_matches": "💕 Şimdiye kadar *{count}* eşleşmeniz var!",
        "your_stats": "📊 *İstatistikleriniz*\n\n❤️ Verilen beğeniler: {given}\n💌 Alınan beğeniler: {received}\n💕 Eşleşmeler: {matches}\n🔥 Bugün kalan swipe: {swipes}",
        "premium_info": "👑 *YourMeet Premium*\n\n✅ Sınırsız swipe\n✅ Sınırsız süper beğeni\n✅ Sizi beğenenleri görün\n✅ Eşleşmede iletişim bilgileri\n✅ Profil boost\n✅ Feed'de öncelik\n✅ Sınırsız sohbet\n\n💰 *Planlar:*\n• 1 Ay — 150 ⭐\n• 3 Ay — 350 ⭐",
        "referral_msg": "🔗 *Referans Linkiniz:*\n\n{link}\n\nHer 3 arkadaş = +10 bonus swipe! 🎁",
        "help_msg": "❓ *Yardım*\n\n/profile — Profili görüntüle\n/matches — Eşleşmeleriniz\n/stats — Aktivite istatistikleri\n/premium — Premium satın al\n/share — Referans linki\n/language — Dil değiştir\n/delete — Hesabı sil\n/about — Uygulama hakkında",
        "about_msg": "💕 *YourMeet*\n\nTelegram üzerinde modern bir flört uygulaması.\n\n👨💻 Geliştirici: @who_is_the-black_hat",
        "delete_confirm": "⚠️ Hesabınızı silmek istediğinizden emin misiniz?\n\nOnaylamak için /confirmdelete yazın.",
        "account_deleted": "✅ Hesabınız silindi. Güle güle!",
        "boost_active": "🚀 *Profil Boost Edildi!*\n\nProfiliniz önümüzdeki 30 dakika boyunca önce gösterilecek!",
        "language_changed": "✅ Dil güncellendi!",
        "not_approved_yet": "⏳ Profiliniz hâlâ inceleniyor. Yakında bilgilendireceğiz!",
    },

    "it": {
        "welcome": "👋 Benvenuto su *YourMeet*!\n\nTrova il tuo partner perfetto da tutto il mondo. 🌍",
        "choose_language": "🌐 Per favore scegli la tua lingua:",
        "language_set": "✅ Lingua impostata su Italiano!",
        "open_app": "💕 Apri YourMeet",
        "profile_submitted": "✅ Il tuo profilo è stato inviato per la revisione!\n\nTi notificheremo una volta approvato. Di solito richiede alcune ore.",
        "profile_approved": "🎉 *Congratulazioni!* Il tuo profilo è stato approvato!\n\nHai *30 swipe gratuiti al giorno*. Apri l'app e inizia a fare match! 💕",
        "profile_approved_verified": "🎉 *Congratulazioni!* Il tuo profilo è approvato e *verificato* ⭐\n\n*30 swipe gratuiti al giorno*. 💕",
        "profile_rejected": "😔 Il tuo profilo non è stato approvato questa volta.\n\nPuoi aggiornare il profilo e inviarlo di nuovo.",
        "profile_banned": "🚫 Il tuo account è stato bannato permanentemente per violazione dei termini.",
        "match_notify": "💕 *È un Match!*\n\nTu e *{name}* vi siete piaciuti a vicenda!\n\nApri l'app per connetterti. 🎉",
        "chat_started": "💬 *Chat iniziata con {name}!*\n\n⏱ Durata: *{duration}*\n\nInvia i tuoi messaggi qui.",
        "chat_ended": "⏰ *Sessione di chat terminata.*\n\nUpgrada a Premium per chat illimitata! 👑",
        "premium_activated": "👑 *Premium Attivato!*\n\nIl tuo premium è attivo fino al *{date}*. 🚀",
        "no_profile": "❌ Non hai ancora un profilo. Apri l'app per crearne uno!",
        "your_profile": "👤 *Il Tuo Profilo*\n\n📛 Nome: {name}\n🎂 Età: {age}\n⚡ Genere: {gender}\n🏙 Città: {city}\n💎 Premium: {premium}\n✅ Stato: {status}",
        "your_matches": "💕 Hai *{count}* match finora!",
        "your_stats": "📊 *Le Tue Statistiche*\n\n❤️ Like dati: {given}\n💌 Like ricevuti: {received}\n💕 Match: {matches}\n🔥 Swipe rimasti oggi: {swipes}",
        "premium_info": "👑 *YourMeet Premium*\n\n✅ Swipe illimitati\n✅ Super like illimitati\n✅ Vedi chi ti ha messo like\n✅ Contatto al match\n✅ Boost profilo\n✅ Priorità nel feed\n✅ Chat illimitata\n\n💰 *Piani:*\n• 1 Mese — 150 ⭐\n• 3 Mesi — 350 ⭐",
        "referral_msg": "🔗 *Il Tuo Link di Referral:*\n\n{link}\n\nOgni 3 amici = +10 swipe bonus! 🎁",
        "help_msg": "❓ *Aiuto*\n\n/profile — Vedi profilo\n/matches — I tuoi match\n/stats — Statistiche\n/premium — Acquista premium\n/share — Link referral\n/language — Cambia lingua\n/delete — Elimina account\n/about — Info app",
        "about_msg": "💕 *YourMeet*\n\nUn'app di incontri moderna su Telegram.\n\n👨💻 Sviluppatore: @who_is_the-black_hat",
        "delete_confirm": "⚠️ Sei sicuro di voler eliminare il tuo account?\n\nDigita /confirmdelete per confermare.",
        "account_deleted": "✅ Il tuo account è stato eliminato. Arrivederci!",
        "boost_active": "🚀 *Profilo Boostato!*\n\nIl tuo profilo sarà mostrato per primo per i prossimi 30 minuti!",
        "language_changed": "✅ Lingua aggiornata!",
        "not_approved_yet": "⏳ Il tuo profilo è ancora in revisione. Ti avviseremo presto!",
    },

    "ja": {
        "welcome": "👋 *YourMeet*へようこそ！\n\n世界中から理想のパートナーを見つけましょう。🌍",
        "choose_language": "🌐 言語を選択してください：",
        "language_set": "✅ 言語が日本語に設定されました！",
        "open_app": "💕 YourMeetを開く",
        "profile_submitted": "✅ プロフィールが審査のために送信されました！\n\n承認されたらお知らせします。通常数時間かかります。",
        "profile_approved": "🎉 *おめでとうございます！* プロフィールが承認されました！\n\n1日*30回の無料スワイプ*が使えます。アプリを開いてマッチングを始めましょう！💕",
        "profile_approved_verified": "🎉 *おめでとうございます！* プロフィールが承認・*認証*されました ⭐\n\n1日*30回の無料スワイプ*。💕",
        "profile_rejected": "😔 今回はプロフィールが承認されませんでした。\n\nプロフィールを更新して再送信できます。",
        "profile_banned": "🚫 利用規約違反のため、アカウントが永久停止されました。",
        "match_notify": "💕 *マッチしました！*\n\nあなたと*{name}*がお互いに好きになりました！\n\nアプリを開いて繋がりましょう。🎉",
        "chat_started": "💬 *{name}とのチャットが始まりました！*\n\n⏱ 時間：*{duration}*\n\nここにメッセージを送ってください。",
        "chat_ended": "⏰ *チャットセッションが終了しました。*\n\n無制限チャットはプレミアムにアップグレードを！👑",
        "premium_activated": "👑 *プレミアム有効化！*\n\nプレミアムは*{date}*まで有効です。🚀",
        "no_profile": "❌ まだプロフィールがありません。アプリを開いて作成してください！",
        "your_profile": "👤 *あなたのプロフィール*\n\n📛 名前：{name}\n🎂 年齢：{age}\n⚡ 性別：{gender}\n🏙 都市：{city}\n💎 プレミアム：{premium}\n✅ ステータス：{status}",
        "your_matches": "💕 現在*{count}*件のマッチがあります！",
        "your_stats": "📊 *あなたの統計*\n\n❤️ 送ったいいね：{given}\n💌 もらったいいね：{received}\n💕 マッチ数：{matches}\n🔥 今日の残りスワイプ：{swipes}",
        "premium_info": "👑 *YourMeetプレミアム*\n\n✅ 無制限スワイプ\n✅ 無制限スーパーいいね\n✅ いいねした人を見る\n✅ マッチ時の連絡先\n✅ プロフィールブースト\n✅ フィードの優先表示\n✅ 無制限チャット\n\n💰 *プラン：*\n• 1ヶ月 — 150 ⭐\n• 3ヶ月 — 350 ⭐",
        "referral_msg": "🔗 *あなたの紹介リンク：*\n\n{link}\n\n友達3人ごとに+10スワイプボーナス！🎁",
        "help_msg": "❓ *ヘルプ*\n\n/profile — プロフィール表示\n/matches — マッチ一覧\n/stats — 活動統計\n/premium — プレミアム購入\n/share — 紹介リンク\n/language — 言語変更\n/delete — アカウント削除\n/about — アプリについて",
        "about_msg": "💕 *YourMeet*\n\nTelegramベースのモダンなマッチングアプリ。\n\n👨💻 開発者：@who_is_the-black_hat",
        "delete_confirm": "⚠️ 本当にアカウントを削除しますか？この操作は取り消せません。\n\n確認するには /confirmdelete と入力してください。",
        "account_deleted": "✅ アカウントが削除されました。さようなら！",
        "boost_active": "🚀 *プロフィールブースト！*\n\n今後30分間、あなたのプロフィールが優先表示されます！",
        "language_changed": "✅ 言語が更新されました！",
        "not_approved_yet": "⏳ プロフィールはまだ審査中です。もうすぐお知らせします！",
    },

    "hi": {
        "welcome": "👋 *YourMeet* में आपका स्वागत है!\n\nदुनिया भर से अपना परफेक्ट पार्टनर खोजें। 🌍",
        "choose_language": "🌐 कृपया अपनी भाषा चुनें:",
        "language_set": "✅ भाषा हिंदी में सेट की गई!",
        "open_app": "💕 YourMeet खोलें",
        "profile_submitted": "✅ आपकी प्रोफ़ाइल समीक्षा के लिए सबमिट की गई!\n\nस्वीकृत होने पर हम आपको सूचित करेंगे। आमतौर पर कुछ घंटे लगते हैं।",
        "profile_approved": "🎉 *बधाई हो!* आपकी प्रोफ़ाइल स्वीकृत हो गई!\n\nआपके पास अब *प्रतिदिन 30 मुफ़्त स्वाइप* हैं। ऐप खोलें और मैचिंग शुरू करें! 💕",
        "profile_approved_verified": "🎉 *बधाई हो!* आपकी प्रोफ़ाइल स्वीकृत और *सत्यापित* हो गई ⭐\n\n*प्रतिदिन 30 मुफ़्त स्वाइप*। 💕",
        "profile_rejected": "😔 इस बार आपकी प्रोफ़ाइल स्वीकृत नहीं हुई।\n\nआप प्रोफ़ाइल अपडेट करके दोबारा सबमिट कर सकते हैं।",
        "profile_banned": "🚫 सेवा की शर्तों का उल्लंघन करने के कारण आपका खाता स्थायी रूप से प्रतिबंधित कर दिया गया है।",
        "match_notify": "💕 *मैच हो गया!*\n\nआप और *{name}* ने एक-दूसरे को पसंद किया!\n\nकनेक्ट करने के लिए ऐप खोलें। 🎉",
        "chat_started": "💬 *{name} के साथ चैट शुरू हुई!*\n\n⏱ अवधि: *{duration}*\n\nयहाँ अपने संदेश भेजें।",
        "chat_ended": "⏰ *चैट सत्र समाप्त हो गया।*\n\nअसीमित चैट के लिए Premium में अपग्रेड करें! 👑",
        "premium_activated": "👑 *Premium सक्रिय!*\n\nआपका Premium *{date}* तक सक्रिय है। 🚀",
        "no_profile": "❌ आपकी अभी तक कोई प्रोफ़ाइल नहीं है। बनाने के लिए ऐप खोलें!",
        "your_profile": "👤 *आपकी प्रोफ़ाइल*\n\n📛 नाम: {name}\n🎂 उम्र: {age}\n⚡ लिंग: {gender}\n🏙 शहर: {city}\n💎 Premium: {premium}\n✅ स्थिति: {status}",
        "your_matches": "💕 अब तक आपके *{count}* मैच हैं!",
        "your_stats": "📊 *आपके आँकड़े*\n\n❤️ दिए गए लाइक: {given}\n💌 मिले लाइक: {received}\n💕 मैच: {matches}\n🔥 आज बचे स्वाइप: {swipes}",
        "premium_info": "👑 *YourMeet Premium*\n\n✅ असीमित स्वाइप\n✅ असीमित सुपर लाइक\n✅ देखें किसने लाइक किया\n✅ मैच पर संपर्क विवरण\n✅ प्रोफ़ाइल बूस्ट\n✅ फ़ीड में प्राथमिकता\n✅ असीमित चैट\n\n💰 *प्लान:*\n• 1 महीना — 150 ⭐\n• 3 महीने — 350 ⭐",
        "referral_msg": "🔗 *आपका रेफरल लिंक:*\n\n{link}\n\nहर 3 दोस्त = +10 बोनस स्वाइप! 🎁",
        "help_msg": "❓ *सहायता*\n\n/profile — प्रोफ़ाइल देखें\n/matches — आपके मैच\n/stats — गतिविधि आँकड़े\n/premium — Premium खरीदें\n/share — रेफरल लिंक\n/language — भाषा बदलें\n/delete — खाता हटाएं\n/about — ऐप के बारे में",
        "about_msg": "💕 *YourMeet*\n\nTelegram पर एक आधुनिक डेटिंग ऐप।\n\n👨💻 डेवलपर: @who_is_the-black_hat",
        "delete_confirm": "⚠️ क्या आप वाकई अपना खाता हटाना चाहते हैं? यह पूर्ववत नहीं किया जा सकता।\n\nपुष्टि के लिए /confirmdelete टाइप करें।",
        "account_deleted": "✅ आपका खाता हटा दिया गया है। अलविदा!",
        "boost_active": "🚀 *प्रोफ़ाइल बूस्ट!*\n\nआपकी प्रोफ़ाइल अगले 30 मिनट तक सबसे पहले दिखाई देगी!",
        "language_changed": "✅ भाषा अपडेट की गई!",
        "not_approved_yet": "⏳ आपकी प्रोफ़ाइल अभी समीक्षाधीन है। हम जल्द ही सूचित करेंगे!",
    },
}


def get(lang: str, key: str, **kwargs) -> str:
    """Get a string in the given language, fallback to English."""
    lang = lang if lang in STRINGS else "en"
    text = STRINGS[lang].get(key) or STRINGS["en"].get(key, "")
    return text.format(**kwargs) if kwargs else text
